### ISSUE TITLE
NodeJS error: ERR_OSSL_EVP_UNSUPPORTED

### ISSUE THREAD

**Issue by rrooij** [roodjong/mijnrood#152]
Starting the docker compose with `docker compose up` results in the node container not properly starting:

```
node-container       | 
node-container       | > watch
node-container       | > encore dev --watch
node-container       | 
node-container       | Running webpack ...
node-container       | 
node-container       | 
node-container       | webpack is watching the files…
node-container       | 
node-container       | node:internal/crypto/hash:68
node-container       |   this[kHandle] = new _Hash(algorithm, xofLen);
node-container       |                   ^
node-container       | 
node-container       | Error: error:0308010C:digital envelope routines::unsupported
node-container       |     at new Hash (node:internal/crypto/hash:68:19)
node-container       |     at Object.createHash (node:crypto:138:10)
node-container       |     at module.exports (/var/www/project/node_modules/webpack/lib/util/createHash.js:135:53)
node-container       |     at NormalModule._initBuildHash (/var/www/project/node_modules/webpack/lib/NormalModule.js:417:16)
node-container       |     at handleParseError (/var/www/project/node_modules/webpack/lib/NormalModule.js:471:10)
node-container       |     at /var/www/project/node_modules/webpack/lib/NormalModule.js:503:5
node-container       |     at /var/www/project/node_modules/webpack/lib/NormalModule.js:358:12
node-container       |     at /var/www/project/node_modules/loader-runner/lib/LoaderRunner.js:373:3
node-container       |     at iterateNormalLoaders (/var/www/project/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
node-container       |     at Array.<anonymous> (/var/www/project/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
node-container       |     at Storage.finished (/var/www/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
node-container       |     at /var/www/project/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
node-container       |     at /var/www/project/node_modules/graceful-fs/graceful-fs.js:123:16
node-container       |     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read/context:68:3) {
node-container       |   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
node-container       |   library: 'digital envelope routines',
node-container       |   reason: 'unsupported',
node-container       |   code: 'ERR_OSSL_EVP_UNSUPPORTED'
node-container       | }
node-container       | 
node-container       | Node.js v20.11.1
node-container       | npm notice 
node-container       | npm notice New minor version of npm available! 10.2.4 -> 10.4.0
node-container       | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.4.0>
node-container       | npm notice Run `npm install -g npm@10.4.0` to update!
node-container       | npm notice 
node-container exited with code 1
```

Probably just updating webpack will solve the problem.

**Comment by rrooij** [comment]
Just running `docker compose run --rm node-service yarn install --force` solved the problem.
